version: '3.4'

services:
  web:
    build:
      context: ../../packages
      dockerfile: Dockerfile.web
      target: development
    restart: on-failure
    volumes:
      - ../../packages/package.json:/app/package.json
      - ../../packages/tslint.json:/app/tslint.json
      - ../../packages/tsconfig.json:/app/tsconfig.json
      - ../../packages/yarn.lock:/app/yarn.lock
      - ../../packages/web/src:/app/web/src
      - ../../packages/web/package.json:/app/web/package.json
      - ../../packages/web/webpack.config.ts:/app/web/webpack.config.ts
      - ../../packages/config/src:/app/config/src
      - ../../packages/config/index.ts:/app/config/index.ts
      - ../../packages/config/package.json:/app/config/package.json
      - ../../packages/core/src:/app/core/src
      - ../../packages/core/index.ts:/app/core/index.ts
      - ../../packages/core/package.json:/app/core/package.json
      - ../../packages/infrastructure/src:/app/infrastructure/src
      - ../../packages/infrastructure/index.ts:/app/infrastructure/index.ts
      - ../../packages/infrastructure/package.json:/app/infrastructure/package.json
      - global-node_modules:/app/node_modules
      - core-node_modules:/app/core/node_modules
      - config-node_modules:/app/config/node_modules
      - infrastructure-node_modules:/app/infrastructure/node_modules
      - web-node_modules:/src/node_modules
    networks:
      - internet
      - backoffice
    links:
      - api

  api:
    build:
      context: ../../packages
      dockerfile: Dockerfile.api
      target: development
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: dt-townies
      DB_PASS: seinwotdt
      DB_PORT: 5432
    networks:
      - backoffice
    volumes:
      - ../../packages/package.json:/app/package.json
      - ../../packages/tslint.json:/app/tslint.json
      - ../../packages/tsconfig.json:/app/tsconfig.json
      - ../../packages/yarn.lock:/app/yarn.lock
      - ../../packages/api/src:/app/api/src
      - ../../packages/api/package.json:/app/api/package.json
      - ../../packages/config/src:/app/config/src
      - ../../packages/config/index.ts:/app/config/index.ts
      - ../../packages/config/package.json:/app/config/package.json
      - ../../packages/core/src:/app/core/src
      - ../../packages/core/index.ts:/app/core/index.ts
      - ../../packages/core/package.json:/app/core/package.json
      - ../../packages/infrastructure/src:/app/infrastructure/src
      - ../../packages/infrastructure/index.ts:/app/infrastructure/index.ts
      - ../../packages/infrastructure/package.json:/app/infrastructure/package.json
      - global-node_modules:/app/node_modules
      - api-node_modules:/app/api/node_modules
      - core-node_modules:/app/core/node_modules
      - config-node_modules:/app/config/node_modules
      - infrastructure-node_modules:/app/infrastructure/node_modules
    links:
      - db
  db:
    image: "postgres:9.6.2-alpine"
    environment:
      - POSTGRES_USER=dt-townies
      - POSTGRES_PASSWORD=seinwotdt
      - POSTGRES_MULTIPLE_DATABASES="dt-townies-test"
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./create_multi_dbs.sh:/docker-entrypoint-initdb.d/create_multi_dbs.sh
      - db-pgdata:/var/lib/postgresql/data
      - ../../tmp/dbdumps:/dbdumps
    networks:
      - backoffice

volumes:
  api-node_modules:
  core-node_modules:
  config-node_modules:
  global-node_modules:
  infrastructure-node_modules:
  web-node_modules:
  db-pgdata:

networks:
  internet:
  backoffice:
